In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"D:\File\Dataset\diabetes_012_health_indicators_BRFSS2015.csv")
df

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
df['Diabetes_012']=df['Diabetes_012'].replace(2,1)

In [4]:
df=df.rename(columns={'Diabetes_012':"Diabetes"})
df.head(11)

,Diabetes,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
5,0.0,1.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,10.0,6.0,8.0
6,0.0,1.0,0.0,1.0,30.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,14.0,0.0,0.0,9.0,6.0,7.0
7,0.0,1.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,1.0,0.0,11.0,4.0,4.0
8,1.0,1.0,1.0,1.0,30.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,0.0,9.0,5.0,1.0
9,0.0,0.0,0.0,1.0,24.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,8.0,4.0,3.0
10,1.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0

In [5]:
df['Diabetes'].loc[df['Diabetes']==1]

8         1.0
10        1.0
13        1.0
17        1.0
23        1.0
         ...
253666    1.0
253668    1.0
253670    1.0
253676    1.0
253679    1.0
Name: Diabetes, Length: 39977, dtype: float64

In [6]:
df_small = df.head(20000)
df_small.shape

(20000, 22)

In [7]:
X=df_small.drop(['Diabetes'],axis=1)
y=df_small['Diabetes']
X

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1.0,0.0,1.0,22.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,20.0,0.0,0.0,13.0,6.0,5.0
19996,0.0,0.0,1.0,23.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,4.0,6.0,8.0
19997,1.0,1.0,1.0,25.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,8.0,6.0,8.0
19998,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,4.0,0.0,30.0,1.0,0.0,7.0,5.0,7.0
19999,0.0,0.0,1.0,32.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,6.0,8.0

In [8]:

correlation_matrix = df_small.corr()
diabetes_corr = correlation_matrix['Diabetes'].sort_values(ascending=False)

print("Tương quan giữa Diabetes và các chỉ số khác:")
print(diabetes_corr)

strongest_feature = diabetes_corr.abs().sort_values(ascending=False).index[1]
print(f"\n=> Chỉ số có tương quan mạnh nhất với Diabetes là: {strongest_feature}")

Tương quan giữa Diabetes và các chỉ số khác:
Diabetes                1.000000
GenHlth                 0.307156
HighBP                  0.263646
BMI                     0.234961
HighChol                0.220266
DiffWalk                0.217743
Age                     0.189612
PhysHlth                0.172673
HeartDiseaseorAttack    0.164875
Stroke                  0.108115
MentHlth                0.080642
CholCheck               0.073677
Smoker                  0.054955
NoDocbcCost             0.039215
AnyHealthcare           0.023111
Sex                     0.009784
Fruits                 -0.045720
Veggies                -0.059691
HvyAlcoholConsump      -0.063687
PhysActivity           -0.115191
Education              -0.130566
Income                 -0.162490
Name: Diabetes, dtype: float64

=> Chỉ số có tương quan mạnh nhất với Diabetes là: GenHlth

In [9]:
cat_feature=[
       'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'  
]

In [10]:
from scipy.stats import chi2_contingency

alpha=0.05
chi2_results={}
for cat in cat_feature:
    contingency=pd.crosstab(df_small[cat],df_small['Diabetes'])
    chi2_stat,p_val,_,_=chi2_contingency(contingency)
    decision="keep feature" if p_val <=alpha else "drop feature"
    chi2_results[cat]={
        'chi2_stat':chi2_stat,
        'p_value':p_val,
        'decision': decision
    }

chi2_df=pd.DataFrame(chi2_results).T
# chi2_df=chi2_df.sort_values(by='p_value')
print(chi2_df)

                        chi2_stat   p_value      decision
HighBP                1388.783722       0.0  keep feature
HighChol               969.164259       0.0  keep feature
CholCheck              107.555517       0.0  keep feature
BMI                    1270.71985       0.0  keep feature
Smoker                  60.108661       0.0  keep feature
Stroke                 232.395932       0.0  keep feature
HeartDiseaseorAttack   542.189741       0.0  keep feature
PhysActivity           264.668828       0.0  keep feature
Fruits                  41.557367       0.0  keep feature
Veggies                 70.855069       0.0  keep feature
HvyAlcoholConsump          80.383       0.0  keep feature
AnyHealthcare           10.424254  0.001244  keep feature
NoDocbcCost             30.413132       0.0  keep feature
GenHlth               1948.368643       0.0  keep feature
MentHlth                 183.5409       0.0  keep feature
PhysHlth               718.030614       0.0  keep feature
DiffWalk               946.759749       0.0  keep feature
Sex                      1.862699  0.172314  drop feature
Age                    796.741573       0.0  keep feature
Education              357.594894       0.0  keep feature
Income                 548.447649       0.0  keep feature

In [11]:
from sklearn.metrics import accuracy_score,f1_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X_train

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
5894,0.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,3.0,0.0,1.0,8.0,6.0,8.0
3728,1.0,1.0,1.0,34.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,3.0,30.0,10.0,1.0,0.0,7.0,5.0,8.0
8958,1.0,1.0,1.0,27.0,0.0,0.0,1.0,1.0,1.0,1.0,...,1.0,0.0,2.0,10.0,0.0,0.0,1.0,10.0,5.0,8.0
7671,0.0,0.0,1.0,23.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,12.0,6.0,6.0
5999,0.0,1.0,1.0,33.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,6.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,1.0,1.0,1.0,27.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,1.0,12.0,4.0,3.0
11964,1.0,1.0,1.0,22.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,3.0,0.0,20.0,1.0,0.0,11.0,6.0,8.0
5390,0.0,0.0,1.0,31.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,6.0,4.0,7.0
860,0.0,0.0,1.0,31.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,3.0,0.0,5.0,1.0,0.0,11.0,6.0,8.0
15795,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,7.0,6.0,8.0

In [14]:
df.columns

Index(['Diabetes', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [15]:
columns_scale=['BMI','GenHlth','MentHlth','PhysHlth','Age','Education','Income']

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [17]:
X_train_scaled

array([[-0.87878556, -0.86137716,  0.20027284, ...,  0.03912403,
         0.95186416,  0.95923306],
       [ 1.13793403,  1.16093165,  0.20027284, ..., -0.28107263,
         0.00432316,  0.95923306],
       [ 1.13793403,  1.16093165,  0.20027284, ...,  0.67951736,
         0.00432316,  0.95923306],
       ...,
       [-0.87878556, -0.86137716,  0.20027284, ..., -0.6012693 ,
        -0.94321785,  0.50118761],
       [-0.87878556, -0.86137716,  0.20027284, ...,  0.99971402,
         0.95186416,  0.95923306],
       [-0.87878556, -0.86137716,  0.20027284, ..., -0.28107263,
         0.95186416,  0.95923306]], shape=(16000, 21))

In [29]:
models={
    'Logistic Regresstion': LogisticRegression(solver='saga', max_iter=2000),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(probability=True),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier()
}

In [24]:
result=[]
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    f1=f1_score(y_test,y_pred,average='weighted')
    result.append({
        'model': name,
        'Accuracy': round(acc,4),
        'F1_score': round(f1,4)
    })

C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [25]:
result

[{'model': 'Logistic Regresstion', 'Accuracy': 0.835, 'F1_score': 0.802},
 {'model': 'KNN', 'Accuracy': 0.8147, 'F1_score': 0.7924},
 {'model': 'SVM', 'Accuracy': 0.8263, 'F1_score': 0.7496},
 {'model': 'Naive Bayes', 'Accuracy': 0.75, 'F1_score': 0.7703},
 {'model': 'Decision Tree', 'Accuracy': 0.7702, 'F1_score': 0.7726}]

In [26]:
from sklearn.model_selection import GridSearchCV

param_grids = {
    'Logistic Regresstion': {
        'C': [0.1, 1, 10], 
        'penalty': ['l1', 'l2']
    },
    'KNN': {
        'n_neighbors': [3, 5, 11],
        'weights': ['uniform', 'distance']
    },
    'SVM': {
        'C': [0.1, 1, 10],
        'kernel': ['linear', 'rbf']
    },
    'Naive Bayes': {
        'var_smoothing': [1e-9, 1e-8] 
    },
    'Decision Tree': {
        'max_depth': [None, 10, 20],
        'min_samples_split': [2, 5, 10]
    }
}

optimized_results = []
best_models = {}

for name, model in models.items():
    print(f"Đang tối ưu hóa {name}...")
   
    grid_search = GridSearchCV(
        estimator=model, 
        param_grid=param_grids[name], 
        cv=5, 
        scoring='accuracy', 
        n_jobs=-1 
    )
    
    grid_search.fit(X_train_scaled, y_train)

    best_model = grid_search.best_estimator_
    best_models[name] = best_model

    y_pred = best_model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    optimized_results.append({
        'Model': name,
        'Best Params': grid_search.best_params_,
        'Optimized Accuracy': round(acc, 4),
        'F1 Score': round(f1, 4)
    })

df_optimized = pd.DataFrame(optimized_results)
print(df_optimized.sort_values(by='Optimized Accuracy', ascending=False))

Đang tối ưu hóa Logistic Regresstion...
Đang tối ưu hóa KNN...
Đang tối ưu hóa SVM...
Đang tối ưu hóa Naive Bayes...
Đang tối ưu hóa Decision Tree...
                  Model                                 Best Params  \
0  Logistic Regresstion                  {'C': 10, 'penalty': 'l1'}
2                   SVM                   {'C': 1, 'kernel': 'rbf'}
1                   KNN   {'n_neighbors': 11, 'weights': 'uniform'}
4         Decision Tree  {'max_depth': 10, 'min_samples_split': 10}
3           Naive Bayes                    {'var_smoothing': 1e-09}

   Optimized Accuracy  F1 Score
0              0.8357    0.8014
2              0.8325    0.7867
1              0.8267    0.7918
4              0.8100    0.7899
3              0.7545    0.7733

In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

standalone_models = {
    'Decision Tree': DecisionTreeClassifier(max_depth=10, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
}

new_standalone_results = []

for name, model in standalone_models.items():
    print(f"Đang phân tích: {name}...")
    model.fit(X_train_scaled, y_train)
    
    y_pred = model.predict(X_test_scaled)
    
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    new_standalone_results.append({
        'Model': name,
        'Accuracy': round(acc, 4),
        'F1 Score': round(f1, 4)
    })
df_comparison = pd.DataFrame(new_standalone_results)

print(df_comparison.sort_values(by='F1 Score', ascending=False))

Đang phân tích: Decision Tree...
Đang phân tích: AdaBoost...
Đang phân tích: Gradient Boosting...
               Model  Accuracy  F1 Score
1           AdaBoost    0.8365    0.8082
2  Gradient Boosting    0.8355    0.8049
0      Decision Tree    0.8105    0.7906

In [33]:
checkfit_results = []
for name, model in models.items():
    model.fit(X_train_scaled, y_train)

    train_pred = model.predict(X_train_scaled)
    test_pred = model.predict(X_test_scaled)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)
    
    checkfit_results.append({
        'Model': name,
        'Train Acc': round(train_acc, 4),
        'Test Acc': round(test_acc, 4),
        'Gap': round(train_acc - test_acc, 4) 
    })

import pandas as pd
print(pd.DataFrame(checkfit_results))

                  Model  Train Acc  Test Acc     Gap
0  Logistic Regresstion     0.8354    0.8357 -0.0004
1                   KNN     0.8611    0.8140  0.0471
2                   SVM     0.8528    0.8325  0.0202
3           Naive Bayes     0.7542    0.7545 -0.0002
4         Decision Tree     0.9989    0.7620  0.2369

In [ ]:
import joblib
joblib.dump(models['Logistic Regresstion'],'Logistic_Regresstion_Diabetes.pkl')
joblib.dump(scaler,'scaler.pkl')
joblib.dump(X.columns.tolist(),'columns.pkl')